### ISSUE TITLE
[feature request] search url param

### ISSUE THREAD

**Issue by ttlns** [Niek/chrome-features#2]
A search url parameter in the form `https://niek.github.io/chrome-features/q=Mutat` would be useful.

Alternative (or additional feature) could also be to add references like
`https://niek.github.io/chrome-features/?pref=MutationEvents` or `https://niek.github.io/chrome-features/#MutationEvents`

could be parsed on load over JS I suppose

**Comment by Niek** [comment]
Good idea, fixed in 798c8eb1559443033f96086777fbef3deb49b2d2

Example: https://niek.github.io/chrome-features/?q=Mutat

**Comment by kaliiiiiiiiii** [comment]
Damn you're fast!
Thx haha

**Comment by ttlns** [comment]
Damn you're fast haha, thanks!
@Niek Eventho when searching manually, it won't redirect automatically to the url
I guess some `#q=Mutat` anchor could be used as a workaround, or a copy url button or similar idk

**Comment by Niek** [comment]
OK, done in b12d668abc5f114c576976da589931657b21c824

For more features, feel free to open a PR ;)

**Comment by ttlns** [comment]
Huh seems like smth broke this, maybe some chromium update?

**Comment by ttlns** [comment]
Yeah looks like the build generated some invalid HTML, and the browser is stripping some stuff to fix it (=> not executing the JS & removing some other stuff)

**Comment by Niek** [comment]
> Yeah looks like the build generated some invalid HTML, and the browser is stripping some stuff to fix it (=> not executing the JS & removing some other stuff)

Fixed now with commit ecd7ace06baeec83e420acd121b8fb0f7f948112
